"""
toolguard.reporters.github
~~~~~~~~~~~~~~~~~~~~~~~~~~
Posts dynamic ToolGuard reliability summaries directly to GitHub Pull Requests 
to enforce CI/CD compliance at the workflow level.
"""

import json
import os
import urllib.request
import urllib.parse
from urllib.error import URLError, HTTPError
from toolguard.core.report import ChainTestReport

def post_pr_comment(report: ChainTestReport, threshold: float) -> None:
    """Post the ToolGuard report to the active GitHub PR."""
    
    token = os.environ.get("GITHUB_TOKEN")
    event_path = os.environ.get("GITHUB_EVENT_PATH")
    
    if not token or not event_path:
        # Not running in a GitHub Action PR context or missing token, skip silently or log
        return

    try:
        with open(event_path, "r", encoding="utf-8") as f:
            event_data = json.load(f)
    except Exception:
        return

    # Extract PR number and repository
    pr_number = event_data.get("pull_request", {}).get("number")
    repo = event_data.get("repository", {}).get("full_name")
    
    if not pr_number or not repo:
        return

    # Construct the Markdown comment
    is_passing = report.reliability >= threshold
    status_icon = "✅" if is_passing else "🚨"
    resolution = "PASS" if is_passing else "BLOCKED"
    
    markdown_comment = f"""## {status_icon} ToolGuard Reliability Check ({resolution})

**Chain:** `{report.chain_name}`
**Reliability Score:** `{report.reliability:.1%}` (Threshold: `{threshold:.0%}`)

"""
    if not is_passing:
        markdown_comment += f"> **Warning:** The PR introduces agent fragility. {len([r for r in report.runs if not r.success])} tools will crash if the LLM hallucinates an unexpected payload.\n\n"
        
    markdown_comment += "### Failure Analysis\n"
    markdown_comment += "```text\n"
    markdown_comment += report.summary()
    markdown_comment += "\n```\n\n"
    markdown_comment += "*Automatically generated by [ToolGuard Auto-Discovery](https://github.com/Harshit-J004/toolguard)*"

    # Post to GitHub API
    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github.v3+json",
        "Content-Type": "application/json"
    }
    data = json.dumps({"body": markdown_comment}).encode("utf-8")

    req = urllib.request.Request(url, data=data, headers=headers, method="POST")
    try:
        with urllib.request.urlopen(req) as response:
            pass # Successfully commented
    except (URLError, HTTPError):
        pass # Silently fail if API rate limited or permissions denied
