"""
toolguard.core.tracer
~~~~~~~~~~~~~~~~~~~~~

Thread-safe context manager for intercepting and strictly asserting
multi-agent tool execution graphs (Golden Traces).
"""
import contextvars
import time
from dataclasses import dataclass, field
from typing import Any

from toolguard.core.errors import ToolGuardTraceMismatchError

@dataclass
class TraceNode:
    """A single captured execution of a tool within a trace."""
    tool_name: str
    inputs: dict[str, Any]
    output: Any
    timestamp: float = field(default_factory=time.time)
    latency_ms: float = 0.0

@dataclass
class TraceLog:
    """The chronological graph of all tools called during a single orchestration."""
    nodes: list[TraceNode] = field(default_factory=list)

    @property
    def path(self) -> list[str]:
        """Returns the chronological sequence of tool names called."""
        return [node.tool_name for node in self.nodes]

    def assert_golden_path(self, expected_path: list[str], ignore_retries: bool = True) -> None:
        """Mathematically assert that the LLM called the exact golden sequence of tools."""
        actual = self.path
        
        if ignore_retries:
            # Collapse consecutive duplicate tool calls generated by AI autonomous retry loops.
            # e.g., ["search", "read", "read", "refund"] collapses to ["search", "read", "refund"]
            collapsed = []
            for tool in actual:
                if not collapsed or collapsed[-1] != tool:
                    collapsed.append(tool)
            actual = collapsed

        if actual != expected_path:
            raise ToolGuardTraceMismatchError(
                f"Golden Trace Assertion Failed!\nExpected: {expected_path}\nActual: {actual}",
                expected_path=expected_path,
                actual_path=actual
            )

    def assert_sequence(self, expected_checkpoints: list[str]) -> None:
        """
        Mathematically asserts that mandatory checkpoints occurred in exact chronological 
        order, allowing for non-deterministic AI intermediate steps.
        Example: assert_sequence(["A", "C"]) is VALID even if the LLM graph was [A, B, C].
        """
        actual = self.path
        
        # Perform Subsequence Traversal Check
        actual_idx = 0
        expected_idx = 0
        
        while actual_idx < len(actual) and expected_idx < len(expected_checkpoints):
            if actual[actual_idx] == expected_checkpoints[expected_idx]:
                expected_idx += 1
            actual_idx += 1
            
        if expected_idx != len(expected_checkpoints):
            raise ToolGuardTraceMismatchError(
                f"Mandatory Sequence Checkpoints Failed!\nCheckpoints Expected: {expected_checkpoints}\nResolved Graph: {actual}",
                expected_path=expected_checkpoints,
                actual_path=actual
            )

# The global context variable that allows recursive/async frameworks to push telemetry
_active_tracker: contextvars.ContextVar["TraceTracker | None"] = contextvars.ContextVar("_active_tracker", default=None)
_global_tracker: "TraceTracker | None" = None  # Fallback for ThreadPoolExecutors

class TraceTracker:
    """Context manager to intercept tool calls for Golden Trace verification."""
    
    def __init__(self):
        self.log = TraceLog()
        self._token = None

    def __enter__(self) -> TraceLog:
        self._token = _active_tracker.set(self)
        return self.log

    def __exit__(self, exc_type, exc_val, exc_tb) -> None:
        if self._token:
            _active_tracker.reset(self._token)
            
    def set_global(self) -> TraceLog:
        """Enable global tracking to survive ThreadPoolExecutor context boundaries."""
        global _global_tracker
        _global_tracker = self
        return self.log
        
    def reset_global(self) -> None:
        global _global_tracker
        if _global_tracker is self:
            _global_tracker = None

    def record_entry(self, tool_name: str, inputs: dict[str, Any]) -> TraceNode:
        """Records tool invocation precisely before Python execution to preserve chronological intent."""
        safe_inputs = {k: str(v)[:2000] for k, v in inputs.items()} if inputs else {}
        node = TraceNode(
            tool_name=tool_name,
            inputs=safe_inputs,
            output=None # Output is injected mid-flight during the `finally` hook
        )
        self.log.nodes.append(node)
        return node
        
    def record_exit(self, node: TraceNode, output: Any) -> None:
        """Injects the final stringified memory state into the DAG node after CPython thread completes."""
        node.output = str(output)[:2000] if output else None
        node.latency_ms = (time.time() - node.timestamp) * 1000

def get_active_tracer() -> "TraceTracker | None":
    """Retrieves the active tracker across threads/async boundaries."""
    return _active_tracker.get() or _global_tracker
