"""
toolguard.cli.commands.replay_cmd
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

`toolguard replay <file.json>` — executes exactly one failing payload
locally against a specific tool for instant debugging and stack traces.
"""

from __future__ import annotations

import importlib.util
import inspect
import json
import sys
from pathlib import Path

import click
from rich.console import Console
from rich.panel import Panel
from rich.syntax import Syntax
from rich.traceback import Traceback

from toolguard.core.validator import GuardedTool

from typing import Callable

console = Console()

def _load_tool_from_path(file_path: str, tool_name: str) -> Callable:
    """Dynamically load a Python file and exact tool by name."""
    path = Path(file_path)
    if not path.exists():
        console.print(f"[red]✗ Original source file not found: {path}[/]")
        raise click.Abort()

    dir_path = str(path.parent.resolve())
    if dir_path not in sys.path:
        sys.path.insert(0, dir_path)

    module_name = path.stem
    spec = importlib.util.spec_from_file_location(module_name, path)
    if not spec or not spec.loader:
        console.print(f"[red]✗ Could not load {path.name}[/]")
        raise click.Abort()

    mod = importlib.util.module_from_spec(spec)
    sys.modules[module_name] = mod

    try:
        spec.loader.exec_module(mod)
    except Exception as e:
        console.print(f"[red]✗ Failed to execute {path.name}: {e}[/]")
        raise click.Abort()

    # Find the tool
    for name, obj in inspect.getmembers(mod):
        # We try to match either the raw function name or the GuardedTool name
        current_name = getattr(obj, "name", getattr(obj, "__name__", ""))
        if current_name == tool_name:
            return obj

    console.print(f"[red]✗ Tool '{tool_name}' not found inside {path.name}[/]")
    raise click.Abort()

@click.command("replay")
@click.argument("failure_file", type=click.Path(exists=True, dir_okay=False))
def replay_cmd(failure_file: str) -> None:
    """⏪ Replay a crashed tool payload locally constraint-free.
    
    Reads a JSON failure file (generated by --dump-failures) and
    injects the exact crashing dictionary directly back into your
    local Python function so you can view the stack trace and debug.
    """
    with open(failure_file, "r", encoding="utf-8") as f:
        try:
            data = json.load(f)
        except json.JSONDecodeError:
            console.print(f"[red]✗ Invalid JSON file: {failure_file}[/]")
            raise click.Abort()

    tool_path = data.get("tool_path")
    tool_name = data.get("tool_name")
    payload = data.get("payload")

    if not tool_path or not tool_name:
        console.print("[red]✗ Invalid failure.json: Missing 'tool_path' or 'tool_name'[/]")
        raise click.Abort()

    console.print(f"\n⏪ [bold cyan]Replaying Production Failure[/]")
    console.print(f"   [dim]Target:[/] {tool_name} (in {Path(tool_path).name})")
    
    # Show payload being injected
    payload_str = json.dumps(payload, indent=2)
    console.print(Panel(
        Syntax(payload_str, "json", theme="monokai", background_color="default"),
        title="[bold red]Injected Crashed Payload[/]",
        border_style="red"
    ))

    # Load tool
    target_func = _load_tool_from_path(tool_path, tool_name)
    
    # If the tool is native GuardedTool, we might want to unwrap it so we can see
    # exactly the underlying python crash, or we just call the base tool. 
    # But usually, calling the tool directly does exactly what we want.
    if isinstance(payload, dict):
        call_args = payload
    else:
        call_args = {"__raw__": payload} # Fallback for primitive types

    # Execute
    console.print(f"\n[bold yellow]⚡ Executing {tool_name}...[/]\n")
    try:
        import asyncio
        if asyncio.iscoroutinefunction(target_func) or getattr(target_func, "_is_async", False):
            if isinstance(payload, dict):
                result = asyncio.run(target_func(**payload))
            else:
                result = asyncio.run(target_func(payload))
        else:
            if isinstance(payload, dict):
                result = target_func(**payload)
            else:
                result = target_func(payload)
                
        console.print(f"✅ [bold green]Replay Succeeded![/] The function did not crash this time.")
        console.print("Returned Output:")
        console.print(result)

    except Exception:
        # We WANT it to crash here, that's the point of replay.
        # Print a beautiful rich traceback
        console.print(Traceback(show_locals=True, width=100))
        console.print(f"\n❌ [bold red]CRASH MATCHED[/] - The tool successfully reproduced the failure locally.")

